### ISSUE TITLE
Running Lumibench benchmarks for --width and --height greater than 128

### ISSUE THREAD

**Issue by anaitha2** [ubc-aamodt-group/vulkan-sim#18]
Hi,
I wanted to run the benchmarks for scene 1, 18, and 21 with width and height high enough (512 maybe) to see the effects of Reflections, Shadows, and AO. However, I was not able to run the scene because the execution gets 'Killed' prematurely in the middle of 'Bind miss... ' execution. The benchmark seems to running perfectly fine for all scenes with 128, 128 dimensions though.

**Comment by lucylufei** [comment]
Hi! The program could possibly be prematurely killed due to memory constraints on your system. 

If you're only looking for the output PPM to view the images, you can change the `gpgpusim.config` file to run a functional simulation only. This would be faster and require less RAM without the full performance simulation but still provide the PPM. You can do this by updating the `-gpgpu_ptx_sim_mode` flag to `1`. 

If this option does not work for you, I can also run the simulation on your behalf and provide you with the images. Thanks!
